AllCops:
  Exclude:
    - 'utility_scripts/**/*'
    - 'data/**/*'
    - '.git/**/*'
  TargetRubyVersion: 2.7.2
  SuggestExtensions: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Max: 150
Metrics/LineLength:
  Max: 100
Style/WordArray:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
